In [206]:
import pandas as pd

In [207]:
participants = pd.read_csv("Participants_LEMON.csv")
lps = pd.read_csv("LPS.csv")
wst = pd.read_csv("WST.csv")
tmt = pd.read_csv("TMT.csv")

# reading files works becouse of pandas ----> import pandas as pd

In [208]:
participants.rename(columns={participants.columns[0]: "ID"}, inplace=True)
lps.rename(columns={lps.columns[0]: "ID"}, inplace=True)
wst.rename(columns={wst.columns[0]: "ID"}, inplace=True)
tmt.rename(columns={tmt.columns[0]: "ID"}, inplace=True)

In [209]:
df = participants.merge(lps, on="ID", how="inner")
df = df.merge(wst, on="ID", how="inner")
df = df.merge(tmt, on="ID", how="inner")

In [210]:
df.shape

(227, 18)

In [211]:
df.head()

,ID,Gender_ 1=female_2=male,Age,LPS_1,LPS_2,WST_1,WST_2,WST_3,WST_4,WST_5,TMT_1,TMT_2,TMT_3,TMT_4,TMT_5,TMT_6,TMT_7,TMT_8
0,sub-010002,1,65-70,16,NaN,29,-0.19,97,98,NaN,52.84,4.0,2.0,NaN,60.1,1,0,NaN
1,sub-010003,1,20-25,17,NaN,28,-0.32,95,97,NaN,18.06,1.0,0.0,NaN,36.5,1,0,NaN
2,sub-010004,1,65-70,18,NaN,31,0.10,101,101,NaN,22.00,1.0,0.0,NaN,104,3,2,NaN
3,sub-010005,2,25-30,16,NaN,34,0.67,110,107,NaN,55.07,4.0,0.0,NaN,98.75,3,1,NaN
4,sub-010006,1,65-70,17,NaN,32,0.26,104,103,NaN,21.15,1.0,0.0,NaN,93.29,3,0,NaN

In [212]:
df.rename(columns={'Gender_ 1=female_2=male': 'Sex'}, inplace=True)

In [213]:
df.rename(columns={'LPS_1': 'LPS score'}, inplace=True)
df.rename(columns={'LPS_2': 'LPS comments'}, inplace=True)

df.rename(columns={'WST_1': 'WST score'}, inplace=True)
df.rename(columns={'WST_2': 'WST z-scale'}, inplace=True)
df.rename(columns={'WST_3': 'WST IQ-scale'}, inplace=True)
df.rename(columns={'WST_4': 'WST Z-scale'}, inplace=True)
df.rename(columns={'WST_5': 'WST comments'}, inplace=True)

df.rename(columns={'TMT_1': 'TMT A time'}, inplace=True)
df.rename(columns={'TMT_2': 'TMT A scale'}, inplace=True)
df.rename(columns={'TMT_3': 'TMT A errors'}, inplace=True)
df.rename(columns={'TMT_4': 'TMT A comments'}, inplace=True)
df.rename(columns={'TMT_5': 'TMT B time'}, inplace=True)
df.rename(columns={'TMT_6': 'TMT B scale'}, inplace=True)
df.rename(columns={'TMT_7': 'TMT B errors'}, inplace=True)
df.rename(columns={'TMT_8': 'TMT B comments'}, inplace=True)

In [214]:
df.head(10)

,ID,Sex,Age,LPS score,LPS comments,WST score,WST z-scale,WST IQ-scale,WST Z-scale,WST comments,TMT A time,TMT A scale,TMT A errors,TMT A comments,TMT B time,TMT B scale,TMT B errors,TMT B comments
0,sub-010002,1,65-70,16,NaN,29,-0.19,97,98,NaN,52.84,4.0,2.0,NaN,60.1,1,0,NaN
1,sub-010003,1,20-25,17,NaN,28,-0.32,95,97,NaN,18.06,1.0,0.0,NaN,36.5,1,0,NaN
2,sub-010004,1,65-70,18,NaN,31,0.10,101,101,NaN,22.00,1.0,0.0,NaN,104,3,2,NaN
3,sub-010005,2,25-30,16,NaN,34,0.67,110,107,NaN,55.07,4.0,0.0,NaN,98.75,3,1,NaN
4,sub-010006,1,65-70,17,NaN,32,0.26,104,103,NaN,21.15,1.0,0.0,NaN,93.29,3,0,NaN
5,sub-010007,1,65-70,17,NaN,32,0.26,104,103,NaN,31.09,2.0,0.0,NaN,60,1,0,NaN
6,sub-010010,2,25-30,21,NaN,33,0.45,107,105,NaN,22.87,1.0,0.0,NaN,39.9,1,0,NaN
7,sub-010012,1,60-65,19,NaN,33,0.45,107,105,NaN,30.73,2.0,0.0,NaN,87.31,3,0,NaN
8,sub-010015,2,20-25,24,NaN,34,0.67,110,107,NaN,26.47,1.0,0.0,NaN,54.44,1,0,NaN
9,sub-010016,1,25-30,21,NaN,37,1.43,122,114,NaN,18.72,1.0,1.0,NaN,35.12,1,0,NaN

In [215]:
"""
COLUMN DESCRIPTION:
--------------------------------------------------------------------------------------
ID
Sex	- 1 is female; 2 is male
Age
--------------------------------------------------------------------------------------
Task:
40 rows with 8 symbols each were presented.
Participants had to identify, in each of the rows, the one symbol which did not fit.
Time limit for the task (40 raws): 3 min.

LPS score - LPS raw data, how many symbol-rows did the participant process correctly
LPS comments
--------------------------------------------------------------------------------------
Task:
Total of 42 word sets with each one real/target word and five distractors/pseudo words
participant has to identify the one target word. NO time limit.

WST score	- WST raw data; how many real words did the pp. recognize correctly
WST z-scale	- (M=0, s=1)
WST IQ-scale - (M=100, s=15)
WST Z-scale - (M=100, s=10)
WST comments
--------------------------------------------------------------------------------------
TMT Task A:
Only numbers (1-25)
Participant has to connect numbers as fast as possible in an ascending order.

TMT Task B:
Numbers and letters (1-13, A-L)
Participant has to connect numbers and letters in an alternating and ascending order as fast as possible.

Trails A:
Perfectly normal= 0-26 sec.;
Normal= 27-39 sec.;
Mild/Moderately Impaired= 40-51 sec.;
Moderately/Severely Impaired= 52 sec.+

Trails B:
Perfectly normal= 0-65 sec.;
Normal= 66-85 sec.;
Mild/Moderately Impaired= 86-120 sec.;
Moderately/Severely Impaired= 121 sec.+

Coding brain functions:
Perfectly normal= 1
Normal= 2
Mild/Moderately Impaired= 3
Moderately/Severely Impaired= 4

TMT A time - time it took to connect numbers (seconds. milliseconds)
TMT A scale	- brain functions based on performance for Trail A (1 - 4)
TMT A errors - how many errors did the pp. make
TMT A comments
TMT B time - time it took to connect numbers and letters (seconds. milliseconds)
TMT B scale - brain functions based on performance for Trail B (1 - 4)
TMT B errors	- how many errors did the pp. make
TMT B comments
--------------------------------------------------------------------------------------
"""

'\nCOLUMN DESCRIPTION:\n--------------------------------------------------------------------------------------\nID\nSex\t- 1 is female; 2 is male\nAge\n--------------------------------------------------------------------------------------\nTask:\n40 rows with 8 symbols each were presented.\nParticipants had to identify, in each of the rows, the one symbol which did not fit.\nTime limit for the task (40 raws): 3 min.\n\nLPS score - LPS raw data, how many symbol-rows did the participant process correctly\nLPS comments\n--------------------------------------------------------------------------------------\nTask:\nTotal of 42 word sets with each one real/target word and five distractors/pseudo words\nparticipant has to identify the one target word. NO time limit.\n\nWST score\t- WST raw data; how many real words did the pp. recognize correctly\nWST z-scale\t- (M=0, s=1)\nWST IQ-scale - (M=100, s=15)\nWST Z-scale - (M=100, s=10)\nWST comments\n--------------------------------------------------------------------------------------\nTMT Task A:\nOnly numbers (1-25)\nParticipant has to connect numbers as fast as possible in an ascending order.\n\nTMT Task B:\nNumbers and letters (1-13, A-L)\nParticipant has to connect numbers and letters in an alternating and ascending order as fast as possible.\n\nTrails A:\nPerfectly normal= 0-26 sec.;\nNormal= 27-39 sec.;\nMild/Moderately Impaired= 40-51 sec.;\nModerately/Severely Impaired= 52 sec.+\n\nTrails B:\nPerfectly normal= 0-65 sec.;\nNormal= 66-85 sec.;\nMild/Moderately Impaired= 86-120 sec.;\nModerately/Severely Impaired= 121 sec.+\n\nCoding brain functions:\nPerfectly normal= 1\nNormal= 2\nMild/Moderately Impaired= 3\nModerately/Severely Impaired= 4\n\nTMT A time - time it took to connect numbers (seconds. milliseconds)\nTMT A scale\t- brain functions based on performance for Trail A (1 - 4)\nTMT A errors - how many errors did the pp. make\nTMT A comments\nTMT B time - time it took to connect numbers and letters (seconds. milliseconds)\nTMT B scale - brain functions based on performance for Trail B (1 - 4)\nTMT B errors\t- how many errors did the pp. make\nTMT B comments\n--------------------------------------------------------------------------------------\n'

In [216]:
age_counts = df['Age'].value_counts().sort_index()
age_summary = age_counts.reset_index()
age_summary.columns = ['Age', 'count']
age_summary

     Age  count
0  20-25     79
1  25-30     60
2  30-35     13
3  35-40      1
4  55-60      4
5  60-65     19
6  65-70     25
7  70-75     22
8  75-80      4

In [217]:
age_map = {
    '20-25': '20-35',
    '25-30': '20-35',
    '30-35': '20-35',
    '55-60': '55-80',
    '60-65': '55-80',
    '65-70': '55-80',
    '70-75': '55-80',
    '75-80': '55-80'
}
df['Age group'] = df['Age'].map(age_map)
df['Age group'].value_counts()

Age group
20-35    152
55-80     74
Name: count, dtype: int64

In [218]:
df = df[df['Age group'].isin(['20-35', '55-80'])] # Lets delete one person from 35-40

In [219]:
df.head(10)

,ID,Sex,Age,LPS score,LPS comments,WST score,WST z-scale,WST IQ-scale,WST Z-scale,WST comments,TMT A time,TMT A scale,TMT A errors,TMT A comments,TMT B time,TMT B scale,TMT B errors,TMT B comments,Age group
0,sub-010002,1,65-70,16,NaN,29,-0.19,97,98,NaN,52.84,4.0,2.0,NaN,60.1,1,0,NaN,55-80
1,sub-010003,1,20-25,17,NaN,28,-0.32,95,97,NaN,18.06,1.0,0.0,NaN,36.5,1,0,NaN,20-35
2,sub-010004,1,65-70,18,NaN,31,0.10,101,101,NaN,22.00,1.0,0.0,NaN,104,3,2,NaN,55-80
3,sub-010005,2,25-30,16,NaN,34,0.67,110,107,NaN,55.07,4.0,0.0,NaN,98.75,3,1,NaN,20-35
4,sub-010006,1,65-70,17,NaN,32,0.26,104,103,NaN,21.15,1.0,0.0,NaN,93.29,3,0,NaN,55-80
5,sub-010007,1,65-70,17,NaN,32,0.26,104,103,NaN,31.09,2.0,0.0,NaN,60,1,0,NaN,55-80
6,sub-010010,2,25-30,21,NaN,33,0.45,107,105,NaN,22.87,1.0,0.0,NaN,39.9,1,0,NaN,20-35
7,sub-010012,1,60-65,19,NaN,33,0.45,107,105,NaN,30.73,2.0,0.0,NaN,87.31,3,0,NaN,55-80
8,sub-010015,2,20-25,24,NaN,34,0.67,110,107,NaN,26.47,1.0,0.0,NaN,54.44,1,0,NaN,20-35
9,sub-010016,1,25-30,21,NaN,37,1.43,122,114,NaN,18.72,1.0,1.0,NaN,35.12,1,0,NaN,20-35

In [220]:
sex_counts = df['Sex'].value_counts().sort_index()
sex_summary = sex_counts.reset_index()
sex_summary.columns = ['Sex', 'count']
sex_summary

   Sex  count
0    1     82
1    2    144

In [221]:
df.groupby('Age group')['LPS score'].mean()

Age group
20-35    21.217105
55-80    15.581081
Name: LPS score, dtype: float64

In [222]:
"""
Participants in the older group showed substantially lower performance in LPS,
reflecting age-related decline in fluid intelligence.
"""

'\nParticipants in the older group showed substantially lower performance in LPS,\nreflecting age-related decline in fluid intelligence.\n'

In [223]:
mean_lps = df['LPS score'].mean()
std_lps  = df['LPS score'].std()

In [224]:
df['LPS z-scale'] = (df['LPS score'] - mean_lps) / std_lps

In [225]:
def Zscore(Xscore):
  mean = df[Xscore].mean()
  std = df[Xscore].std()
  return (df[Xscore] - mean) / std


# here I created function so i can do same code twice with proper call.

In [226]:
df['LPS z-scale2'] = Zscore('LPS score')

In [227]:
df.head(10)

,ID,Sex,Age,LPS score,LPS comments,WST score,WST z-scale,WST IQ-scale,WST Z-scale,WST comments,...,TMT A scale,TMT A errors,TMT A comments,TMT B time,TMT B scale,TMT B errors,TMT B comments,Age group,LPS z-scale,LPS z-scale2
0,sub-010002,1,65-70,16,NaN,29,-0.19,97,98,NaN,...,4.0,2.0,NaN,60.1,1,0,NaN,55-80,-0.794833,-0.794833
1,sub-010003,1,20-25,17,NaN,28,-0.32,95,97,NaN,...,1.0,0.0,NaN,36.5,1,0,NaN,20-35,-0.559095,-0.559095
2,sub-010004,1,65-70,18,NaN,31,0.10,101,101,NaN,...,1.0,0.0,NaN,104,3,2,NaN,55-80,-0.323357,-0.323357
3,sub-010005,2,25-30,16,NaN,34,0.67,110,107,NaN,...,4.0,0.0,NaN,98.75,3,1,NaN,20-35,-0.794833,-0.794833
4,sub-010006,1,65-70,17,NaN,32,0.26,104,103,NaN,...,1.0,0.0,NaN,93.29,3,0,NaN,55-80,-0.559095,-0.559095
5,sub-010007,1,65-70,17,NaN,32,0.26,104,103,NaN,...,2.0,0.0,NaN,60,1,0,NaN,55-80,-0.559095,-0.559095
6,sub-010010,2,25-30,21,NaN,33,0.45,107,105,NaN,...,1.0,0.0,NaN,39.9,1,0,NaN,20-35,0.383856,0.383856
7,sub-010012,1,60-65,19,NaN,33,0.45,107,105,NaN,...,2.0,0.0,NaN,87.31,3,0,NaN,55-80,-0.087619,-0.087619
8,sub-010015,2,20-25,24,NaN,34,0.67,110,107,NaN,...,1.0,0.0,NaN,54.44,1,0,NaN,20-35,1.091070,1.091070
9,sub-010016,1,25-30,21,NaN,37,1.43,122,114,NaN,...,1.0,1.0,NaN,35.12,1,0,NaN,20-35,0.383856,0.383856

In [228]:
df.groupby('Age group')['LPS z-scale'].mean()

Age group
20-35    0.435036
55-80   -0.893588
Name: LPS z-scale, dtype: float64

In [229]:
df.groupby('Age group')['WST score'].mean()

Age group
20-35    32.881579
55-80    32.945946
Name: WST score, dtype: float64

In [230]:
"""
Practically no difference.
WST measures vocabulary and linguistic knowledge.
This function increases into adulthood then remains stable for a very long time.

Cognitive aging in this sample does not apply to verbal knowledge and this is healthy signal from the data.
"""

'\nPractically no difference.\nWST measures vocabulary and linguistic knowledge.\nThis function increases into adulthood then remains stable for a very long time.\n\nCognitive aging in this sample does not apply to verbal knowledge and this is healthy signal from the data.\n'

In [231]:
df.groupby('Age group')['WST z-scale'].mean()

Age group
20-35    0.511908
55-80    0.552838
Name: WST z-scale, dtype: float64

In [232]:
df['TMT A rev'] = 5 - df['TMT A scale']
df['TMT B rev'] = 5 - df['TMT B scale']

# Now 4 = best, 1 = worst

In [233]:
# old way:
df['TMT A z-scale'] = (df['TMT A rev'] - df['TMT A rev'].mean()) / df['TMT A rev'].std()
df['TMT B z-scale'] = (df['TMT B rev'] - df['TMT B rev'].mean()) / df['TMT B rev'].std()

# now with function usage:
df['TMT A z-scale2'] = Zscore('TMT A rev')
df['TMT B z-scale2'] = Zscore('TMT B rev')

In [234]:
df.groupby('Age group')[['TMT A z-scale2', 'TMT B z-scale2']].mean()

           TMT A z-scale2  TMT B z-scale2
Age group
20-35            0.400092        0.459717
55-80           -0.833067       -0.944283

In [235]:
df.head(10)

,ID,Sex,Age,LPS score,LPS comments,WST score,WST z-scale,WST IQ-scale,WST Z-scale,WST comments,...,TMT B comments,Age group,LPS z-scale,LPS z-scale2,TMT A rev,TMT B rev,TMT A z-scale,TMT B z-scale,TMT A z-scale2,TMT B z-scale2
0,sub-010002,1,65-70,16,NaN,29,-0.19,97,98,NaN,...,NaN,55-80,-0.794833,-0.794833,1.0,4,-2.666774,0.632852,-2.666774,0.632852
1,sub-010003,1,20-25,17,NaN,28,-0.32,95,97,NaN,...,NaN,20-35,-0.559095,-0.559095,4.0,4,0.855873,0.632852,0.855873,0.632852
2,sub-010004,1,65-70,18,NaN,31,0.10,101,101,NaN,...,NaN,55-80,-0.323357,-0.323357,4.0,2,0.855873,-1.655540,0.855873,-1.655540
3,sub-010005,2,25-30,16,NaN,34,0.67,110,107,NaN,...,NaN,20-35,-0.794833,-0.794833,1.0,2,-2.666774,-1.655540,-2.666774,-1.655540
4,sub-010006,1,65-70,17,NaN,32,0.26,104,103,NaN,...,NaN,55-80,-0.559095,-0.559095,4.0,2,0.855873,-1.655540,0.855873,-1.655540
5,sub-010007,1,65-70,17,NaN,32,0.26,104,103,NaN,...,NaN,55-80,-0.559095,-0.559095,3.0,4,-0.318343,0.632852,-0.318343,0.632852
6,sub-010010,2,25-30,21,NaN,33,0.45,107,105,NaN,...,NaN,20-35,0.383856,0.383856,4.0,4,0.855873,0.632852,0.855873,0.632852
7,sub-010012,1,60-65,19,NaN,33,0.45,107,105,NaN,...,NaN,55-80,-0.087619,-0.087619,3.0,2,-0.318343,-1.655540,-0.318343,-1.655540
8,sub-010015,2,20-25,24,NaN,34,0.67,110,107,NaN,...,NaN,20-35,1.091070,1.091070,4.0,4,0.855873,0.632852,0.855873,0.632852
9,sub-010016,1,25-30,21,NaN,37,1.43,122,114,NaN,...,NaN,20-35,0.383856,0.383856,4.0,4,0.855873,0.632852,0.855873,0.632852

In [236]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

# those imports are not at the beginning to show where machine learning comes in. Those imports are used for 1) Testing, 2) Logistic Regression, 3) resaults

In [237]:
# Features
X = df[['LPS z-scale2', 'WST z-scale', 'TMT A z-scale2', 'TMT B z-scale2']]

# Target
y = df['Age group'].map({'20-35':0, '55-80':1}) # 0 = young; 1 = old

In [238]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y #stratify keeps proportions in young/old for train and test
)

# from sklearn.model_selection import train_test_split <-- this testing works becouse of this import

In [239]:
# model = LogisticRegression()
# model.fit(X_train, y_train)

# here we have problem 1 person has missing values

In [240]:
X.isna().sum()

LPS z-scale2      0
WST z-scale       0
TMT A z-scale2    1
TMT B z-scale2    0
dtype: int64

In [241]:
X_clean = X.dropna()
y_clean = y[X_clean.index]

In [242]:
X_clean.isna().sum()

LPS z-scale2      0
WST z-scale       0
TMT A z-scale2    0
TMT B z-scale2    0
dtype: int64

In [243]:
X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y_clean, test_size=0.3, random_state=42, stratify=y_clean
)

# from sklearn.model_selection import train_test_split <-- this testing works becouse of this import

In [244]:
model = LogisticRegression() # This line works becouse of this import -> from sklearn.linear_model import LogisticRegression
model.fit(X_train, y_train)

LogisticRegression()

In [245]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # P(old)

# Accuracy
acc = accuracy_score(y_test, y_pred)
# AUC
auc = roc_auc_score(y_test, y_prob)
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("ROC-AUC:", auc)
print("Confusion matrix:\n", cm)


# accuracy_score, roc_auc_score, confusion_matrix works becouse of this import -> from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

Accuracy: 0.8970588235294118
ROC-AUC: 0.9278656126482213
Confusion matrix:
 [[42  4]
 [ 3 19]]

In [246]:
"""
Accuracy → „did the model guess correctly 0/1”
ROC-AUC → „can the model distinguish between young and old regardless of the threshold”

Accuracy: 89.7%
ROC-Accuracy: 92.8%

Confusion matrix:

	            Predicted young	| Predicted old
Actual young	       42	              4
Actual old	          3	             19
"""

'\nAccuracy → „did the model guess correctly 0/1”\nROC-AUC → „can the model distinguish between young and old regardless of the threshold”\n\nAccuracy: 89.7%\nROC-Accuracy: 92.8%\n\nConfusion matrix:\n\n\t            Predicted young\t| Predicted old\nActual young\t       42\t              4\nActual old\t          3\t             19\n'